predio/urls.py
from django.urls import path
from . import views
from .views import Predio, PredioForm, PredioCreate, PredioDelete,  PredioList, PredioUpdate

app_name = 'predio'
urlpatterns = [
    path('search', views.search, name='predio_filtrar'),
    path('nuevo', PredioCreate.as_view(), name='predio_crear'),
    path('listar', PredioList.as_view(), name= 'predio_listar'),
    path('editar/<int:pk>', PredioUpdate.as_view(), name= 'predio_editar'),
    path('eliminar/<int:pk>', PredioDelete.as_view(), name= 'predio_eliminar'),
]

propietario/urls.py
from django.urls import path
from . import views
from .views import Propietario, PropietarioForm, PropietarioList, PropietarioCreate, PropietarioDelete, PropietarioUpdate

app_name = 'propietario'
urlpatterns = [
    path('search', views.search, name='propietario_filter'),
    path('nuevo', PropietarioCreate.as_view(), name='propietario_crear'),
    path('listar', PropietarioList.as_view(), name= 'propietario_listar'),
    path('editar/<int:pk>', PropietarioUpdate.as_view(), name= 'propietario_editar'),
    path('eliminar/<int:pk>', PropietarioDelete.as_view(), name= 'propietario_eliminar'),
]

pruebadev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('predio/', include('predio.urls')),
    path('propietario/', include('propietario.urls')),
    path('login', auth_views.LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
]

predio/models.py
from django.db import models


# Create your models here.

class Predio(models.Model):
    TIPO_CHOICES = (
        ('urbano','Urbano'),
        ('rural','Rural'),
    )
    matricula_inmobiliaria = models.IntegerField(unique=True, primary_key=True, verbose_name='matricula inmobiliaria')
    cedula_catastral = models.CharField(max_length=50, verbose_name='cedula catastral')
    tipo = models.CharField(verbose_name='tipo', max_length=6, choices=TIPO_CHOICES)
    direccion_predio = models.CharField(max_length=255, verbose_name='direccion predio', blank=True, null=True )
    nombre_predio = models.CharField(max_length=128, verbose_name='nombre predio',blank=True , null=True)

    class Meta:
        verbose_name = "predio"
        verbose_name_plural = "predios"
        ordering = ["-matricula_inmobiliaria"]

    def __str__(self):
        return '{}{}{}{}{}'.format(self.matricula_inmobiliaria, self.cedula_catastral, self.tipo,self.direccion_predio, self.nombre_predio)

propietario/models.py
from django.db import models
from predio.models import Predio


# Create your models here.
class Propietario(models.Model):
    cedula_ciudadania = models.IntegerField(unique=True, primary_key=True, verbose_name='cedula ciudadania')
    nombre = models.CharField(max_length=128)
    matricula_inmobiliaria = models.ManyToManyField(Predio,blank=True)


    class Meta:
        verbose_name = "propietario"
        verbose_name_plural = "propietarios"


    def __str__(self):
        return '{}{}{}'.format(self.cedula_ciudadania, self.nombre, self.matricula_inmobiliaria)

predio/forms.py
from django import forms
from predio.models import Predio


class PredioForm(forms.ModelForm):
    class Meta:
        model = Predio


        fields = [
            'matricula_inmobiliaria',
            'cedula_catastral',
            'tipo',
            'direccion_predio',
            'nombre_predio',
            ]

        def __init__(self, *args, **kwargs):
            super(PredioForm, self).__init__(*args, **kwargs)
            if 'tipo' == 'urbano':
                self.fields['nombre_predio'].disabled = True
            else:
                self.fields['direccion_predio'].disabled = True
        # if 'tipo' == 'urbano':
        #     prop('nombre_predio')
        # else:
        #     fields.exclude('direccion_predio')

       # labels = {
       #      'matricula_inmobiliaria': 'matricula inmobiliaria',
       #      'cedula_catastral': 'cedula catastral',
       #      'tipo' : 'tipo',
       #      'direccion_predio': 'direccion predio',
       #      'nombre_predio' : 'nombre predio',
       #  }
       #
       #  TIPO_CHOICES = [
       #      ('urbano','Urbano'),
       #      ('rural', 'Rural')
       #  ]
       #
       #  widgets = {
       #      'matricula_inmobiliaria': forms.TextInput( attrs={'class':'form-control'}),
       #      'cedula_catastral': forms.TextInput( attrs={'class':'form-control'}),
       #      'tipo' : forms.CharField(label="Tipo de predio es:", widget=forms.Select(choices=TIPO_CHOICES)),
       #      'direccion_predio': forms.TextInput( attrs={'class':'form-control'}),
       #      'nombre_predio': forms.TextInput( attrs={'class':'form-control'}),
       #  }

propietario/forms.py
from django import forms
from propietario.models import Propietario

class PropietarioForm(forms.ModelForm):
    class Meta:
        model = Propietario

        fields = [
            'cedula_ciudadania',
            'nombre',
            'matricula_inmobiliaria',
         ]
        # labels = {
        #     'cedula_ciudadania': 'Cedula de Ciudadania Propietario',
        #     'nombre': 'Nombre Propietario',
        # }
        # widgets = {
        #     'cedula_ciudadania':forms.TextInput(attrs={'class':'form-control'}),
        #     'nombre': forms.TextInput(attrs={'class':'form-control'}),
        # }

predio/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from predio.forms import PredioForm
from predio.models import Predio
from django.shortcuts import render
from .filters import PredioFilter


# Create your views here.


def search(request):
    predio_filtrar = Predio.objects.all(cedula_catastral__icontains=request.Get.buscar, tipo__icontains=request.Get.buscar, direccion_predio__icontains=request.Get.buscar, nombre_predio__icontains=request.Get.buscar)
    predio_filter = PredioFilter(request.GET, queryset=predio_filtrar)
    return render(request, 'predio/predio_listar.html', {'filter': predio_filter})


class PredioList(ListView):
    model = Predio
    template_name = 'predio/predio_listar.html'



class PredioCreate(CreateView):
    model = Predio
    form_class = PredioForm
    template_name = 'predio/predio_form.html'
    success_url = reverse_lazy('predio:predio_listar')


class PredioUpdate(UpdateView):
    model = Predio
    form_class = PredioForm
    template_name = 'predio/predio_form.html'
    success_url = reverse_lazy('predio:predio_listar')


class PredioDelete (DeleteView):
    model = Predio
    template_name = 'predio/predio_eliminar.html'
    success_url = reverse_lazy('predio:predio_listar')

propietario/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from propietario.forms import PropietarioForm
from propietario.models import Propietario
from django.shortcuts import render
from .filters import PropietarioFilter


# Create your views here.


def search(request):
    propietario_filtrar = Propietario.objects.all(cedula_ciudadania__icontains=request.Get.buscar, nombre__icontains= request.Get.buscar )
    propietario_filter = Propietario(request.GET, queryset= propietario_filtrar)
    return render(request, 'propietario/propietario_listar.html', {'filter': propietario_filter})


class PropietarioList(ListView):
    model = Propietario
    template_name = 'propietario/propietario_listar.html'


class PropietarioCreate(CreateView):
    model = Propietario
    form_class = PropietarioForm
    template_name = 'propietario/propietario_form.html'
    success_url = reverse_lazy('propietario:propietario_listar')

class PropietarioUpdate(UpdateView):
    model = Propietario
    form_class = PropietarioForm
    template_name = 'propietario/propietario_form.html'
    success_url = reverse_lazy('propietario:propietario_listar')

class PropietarioDelete(DeleteView):
    model = Propietario
    template_name = 'propietario/propietario_delete.html'
    success_url = reverse_lazy('propietario:propietario_listar')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<title>{% block title %} Pruebadev {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Pruebadev</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Predios
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'predio:predio_crear' %}">Crear Predio</a>
          <a class="dropdown-item" href="{% url 'predio:predio_listar' %}">Listado de Predios</a>
        </div>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Propietarios
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'propietario:propietario_crear' %}">Registrar propietarios</a>
          <a class="dropdown-item" href="{% url 'propietario:propietario_listar' %}">Listado propietarios</a>
        </div>
    </ul>
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown"><a href="{% url 'logout' %}" onclick="pageTracker._link(this.href); return false;">Logout</a></li>
      </ul>
  </div>
</nav>
{%  block barra_busqueda%}
<div class="container">
    <div class="row">
        <div class="col-md-12 search">
            <form method="get">
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control" placeholder="Buscar" name="buscar" value="{{ request.Get.buscar }}">
                        <span class="input-group-list">
                            <i class="icon icon-search"></i>
                            <button type="submit" class="boton btn-sucess">Buscar</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
	{% block content %}{% endblock %}
	{% block footer %}{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/predio/predio_eliminar.html
{% extends 'base.html' %}

{% block content%}
<form method ="post">
    {%csrf_token%}
    <h3>Desea eliminar el registro de {{ predio.matricula_inmobiliaria }}?</h3>
    <button class="btm btn-danger" type="submit" > Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'predio:predio_listar' %}" ></a>
</form>
{% endblock%}

templates/predio/predio_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <form method ="post">
        {% csrf_token %}

        {{ form.as_p}}
        <button type="submit">Guardar</button>
    </form>
     <script src="{% static 'js/formpredio.js' %}"></script>
{% endblock %}

<style>
body {
  background: white;
    text-align: center;
}
</style>

templates/predio/predio_listar.html
{% extends 'base.html'%}
{% block content%}

<table class="table table-bordered">
    <thead>
        <tr>
            <td>matricula inmobiliaria</td>
            <td>cedula catastral</td>
            <td>tipo</td>
            <td>direccion predio</td>
            <td>nombre predio</td>
            <td>Modificar</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
            {% for predio in object_list %}
            <tr>
                <td>{{predio.matricula_inmobiliaria}}</td>
                <td>{{predio.cedula_catastral}}</td>
                <td>{{predio.tipo}}</td>
                <td>{{predio.direccion_predio}}</td>
                <td>{{predio.nombre_predio}}</td>
                <td>
                    <a class="btn btn-primary" href="{%url 'predio:predio_editar' pk=predio.matricula_inmobiliaria %}">Editar</a>
                    <a class="btn btn-danger" href="{%url 'predio:predio_eliminar' pk=predio.matricula_inmobiliaria  %}">Eliminar</a>
                </td>
            </tr>
            {%endfor%}
        {% else %}
            <form method="get">
                {{ filter.form.as_p }}
                <button type="submit">Search</button>
            </form>
          <ul>
              {% for predio in filter.qs %}
                <li>{{ predio.cedula_catastral}} - {{ predio.tipo }} - {{ predio.direccion_predio }} - {{ predio.nombre_predio}}</li>
              {% endfor %}
          </ul>
        {% endif %}
    </tbody>
</table>
{% endblock %}

templates/propietario/propietario_delete.html
{% extends 'base.html' %}

{% block content%}
<form method ="post">
    {%csrf_token%}
    <h3>Desea eliminar el registro de {{ propietario.nombre }}?</h3>
    <button class="btm btn-danger" type="submit" > Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'propietario:propietario_listar' %}" ></a>
</form>
{% endblock%}

templates/propietario/propietario_form.html
{% extends 'base.html' %}
{% block content %}
    <form method ="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

templates/propietario/propietario_listar.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Propietarios{% endblock %}
{% block content%}
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Cedula de Ciudadania</td>
                <td>Nombre</td>
            </tr>
        </thead>
        <tbody>


                {% if object_list %}

                    {% for propietario in object_list %}
                        <tr>
                            <td>{{ propietario.cedula_ciudadania}}</td>
                            <td>{{ propietario.nombre}}</td>
                            <td>
                                <a class="btn btn-primary" href="{%url 'propietario:propietario_editar' pk=propietario.cedula_ciudadania %}">Editar</a>
                                <a class="btn btn-danger" href="{%url 'propietario:propietario_eliminar' pk=propietario.cedula_ciudadania %}">Eliminar</a>
                            </td>
                        </tr>
                    {%endfor%}
                {%else%}
                    <form method="get">
                {{ filter.form.as_p }}
                <button type="submit">Search</button>
            </form>
          <ul>
              {% for propìetario in filter.qs %}
                <li>{{ propietario.cedula_ciudadania}} - {{ propietario.nombre }}</li>
              {% endfor %}
          </ul>
                {% endif %}
        </tbody>
    </table>
{% endblock%}